### ISSUE TITLE
[Tarefa] Verificação de e-mail

### ISSUE THREAD

**Issue by Deullam** [Hubvet8/hubvet-api#69]
## Descrição
Breve resumo do que é essa tarefa, descreva o trabalho a ser realizado
 - Deve fazer a verificação de e-mail

#### Endpoint
`/api/emails/{id}/verificar`

#### UML (Class/DB/Tabela)

Dados |  Tipo
----|----
Texto 1 | String
Número 2 | Integer,int
Booleano 3 | boolean
Monetáio 4 | Float
Data 5 | datetime
Hora 6 | Time
Data e Hora | datetime
Lista 7 | Enum/Array/JSON/JSONB

#### TODO
- [ ] UML
- [ ] Documentação da API
- [ ] Testes

- [ ] Ao enviar uma requisição para o endpoint um e-mail com um link/token único deverá ser enviado para o e-mail correspondente ao usuário(id)
  - [ ] Se o e-mail já foi verificado não enviar novo e-mail de verificação
  - [ ] Se o e-mail não pertence ao usuário solicitante, não enviar e-mail de solicitação
  - [ ] Solicitar senha para confirmar a verificação do e-mail
  - [ ] Um e-mail só pode ser confirmado dentro do seu período de validade

#### Documentação
https://dev.hubvet.app/docs#<URI>
