### ISSUE TITLE
[Tarefa] Recuperação de senha (por e-mail)

### ISSUE THREAD

**Issue by Deullam** [Hubvet8/hubvet-api#73]
## Descrição
 - Deve fazer a recuperação de senha por e-mail

#### Endpoint
`/api/usuario/{email}/recuperar`

#### UML (Class/DB/Tabela)

Dados |  Tipo
----|----
email | BigInt

#### TODO
- [ ] UML
- [ ] Documentação da API
- [ ] Testes

- [ ] Ao enviar uma requisição para o endpoint  deve ser gerado um link único deverá ser enviado para o e-mail correspondente 
- [ ] Ao clicar no link a pessoa será redirecionada para uma página onde irá cadastrar uma nova senha 
  - [ ] Após utilizar o link ele deve ser desativado
  - [ ] Se o e-mail não existir ao usuário solicitante, não enviar e-mail de solicitação
  - [ ] Uma nova senha só pode ser confirmado dentro do seu período de validade

#### Documentação
https://dev.hubvet.app/docs#<URI>

#### UI Hubvet8/hubvet-web#
https://github.com/Hubvet8/hubvet-web/issues/161
